force-app/main/default/objects/Product2/fields/AvailableInventory__c.field-meta.xml
<CustomField>
    <fullName>AvailableInventory__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Available Inventory</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/IsPreOrder__c.field-meta.xml
<CustomField>
    <fullName>IsPreOrder__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pre Order Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/shopping-cart/classes/ProductService.cls
public with sharing class ProductService {
    public class ProductServiceException extends Exception {
        //TO DO
    }
    private static ProductService instance;

    public static ProductService getInstance() {
        if (instance == null) {
            instance = new ProductService();
        }
        return instance;
    }
    public List<Product2> getAvailableProducts() {
        try {
            return [
                SELECT
                    Id,
                    AvailableInventory__c,
                    DisplayUrl,
                    IsPreOrder__c,
                    ProductCode,
                    Description,
                    Name,
                    StockKeepingUnit,
                    Seller.Name,
                    QuantityUnitOfMeasure
                FROM Product2
                WHERE AvailableInventory__c > 0 AND IsActive = :true
                WITH SECURITY_ENFORCED
            ];
        } catch (Exception e) {
            throw new ProductServiceException(e.getMessage());
        }
    }
    public Map<Id, Decimal> getProductStandardPrice(Set<Id> productIds) {
        Map<Id, Decimal> productAndPrice = new Map<Id, Decimal>();
        for (PricebookEntry pbe : [
            SELECT UnitPrice, Product2Id
            FROM PricebookEntry
            WHERE
                IsActive = :true
                AND Pricebook2.IsStandard = :true
                AND Pricebook2.IsActive = :true
                AND Product2Id IN :productIds
            WITH SECURITY_ENFORCED
        ]) {
            if (!productAndPrice.containsKey(pbe.Product2Id)) {
                productAndPrice.put(pbe.Product2Id, pbe.UnitPrice);
            }
        }
        return productAndPrice;
    }
}